project:
  type: website
  output-dir: docs

website:
  title: "Diverse Data Hub"
  navbar:
    left:
      - href: index.qmd
        text: Welcome
      - datasets.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: false
    page-layout: full
    toc-location: right



