project:
  type: website

website:
  title: "Diverse Data Hub"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - datasets.qmd
      - notebooks.qmd
      - template.qmd

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true



