project:
  type: website

website:
  title: "Capstone Proposal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - datasets.qmd
      - notebooks.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



